image: viaduck/ci

stages:
    - build         # contains build and test and deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    ICU_BUILD_VERSION: "74.1"
    ICU_BUILD_HASH: "86ce8e60681972e60e4dcb2490c697463fcec60dd400a5f9bffba26d0b52b8d0"
    PREBUILT_AUTH: "$PREBUILT_USER:$PREBUILT_PASSWORD"
    ANDROID_PLATFORM: "android-23"
    
build:linux-x86_64:
    script:
        - mkdir build-linux-x86_64
        - cd build-linux-x86_64
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH
        - ninja
        - ../scripts/upload_result.sh x86_64-linux icu_host
    stage: build
    only:
        - master

build:windows-x86_64:
    image: viaduck/ci:mingw
    script:
        - update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix        # fix c++11 threading support on debian
        - update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
        - mkdir build-windows-x86_64
        - cd build-windows-x86_64
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=x86_64-w64-mingw32 -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH -DCMAKE_TOOLCHAIN_FILE=../cmake-modules/toolchains/mingw64-x86_64.cmake
        - ninja
        - cp icu_cross-build/lib/*.dll icu_cross/lib/ # workaround for missing copy step
        - for file in icu_cross/lib/icudt*.dll; do mv $file ${file//icudt./icudt}; done # workaround for wrong dll name
        - ../scripts/upload_result.sh x86_64-w64-mingw32 icu_cross
    stage: build
    only:
        - master

build:android-arm64-v8a:
    image: viaduck/ci:android
    script:
        - echo $ANDROID_NDK
        - mkdir build-android-arm64-v8a
        - cd build-android-arm64-v8a
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - ninja
        - ../scripts/upload_result.sh arm64-v8a-android icu_cross
    stage: build
    only:
        - master
        
build:android-armeabi-v7a:
    image: viaduck/ci:android
    script:
        - echo $ANDROID_NDK
        - mkdir build-android-armeabi-v7a
        - cd build-android-armeabi-v7a
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=armeabi-v7a -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - ninja
        - ../scripts/upload_result.sh armeabi-v7a-android icu_cross
    stage: build
    only:
        - master
        
build:android-i686:
    image: viaduck/ci:android
    script:
        - echo $ANDROID_NDK
        - mkdir build-android-i686
        - cd build-android-i686
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86 -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - ninja
        - ../scripts/upload_result.sh i686-android icu_cross
    stage: build
    only:
        - master
        
build:android-x86_64:
    image: viaduck/ci:android
    script:
        - echo $ANDROID_NDK
        - mkdir build-android-x86_64
        - cd build-android-x86_64
        - cmake -GNinja ../ -DBUILD_ICU=ON -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DICU_BUILD_HASH=$ICU_BUILD_HASH -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - ninja
        - ../scripts/upload_result.sh x86_64-android icu_cross
    stage: build
    only:
        - master
